version: "3.3"

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: task4_front
    expose:
      - "9000"
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: task4_back
    expose:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: task5_proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
