version: "3.3"

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: task4_front
    ports:
      - "9000:9000"
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: task4_back
    ports:
      - "5252:5252"
